services:
  local:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    volumes:
      - ./:/app
      - ./docker/local/ssh/id_rsa:/root/.ssh/id_rsa
      - ./docker/local/ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ./docker/local/ssh_config:/etc/ssh/ssh_config

  production:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    volumes:
      - ./TestDeployer-prod:/app
    ports:
      - '9000:9000'
      - '22:22'

  webserver:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./TestDeployer:/app
    ports:
      - '8000:80'