services:
  local:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    volumes:
      - ./:/app
      - ./docker/local/ssh/id_rsa:/root/.ssh/id_rsa
      - ./docker/local/ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ./docker/local/ssh_config:/etc/ssh/ssh_config

  production:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    volumes:
      - ../TestDeployer-prod:/app
      - ./docker/production/ssh/id_rsa:/root/.ssh/id_rsa
      - ./docker/production/ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ./docker/production/ssh_config:/etc/ssh/ssh_config
    ports:
      - '9000:9000'
      - '22:22'

  webserver:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./TestDeployer-prod:/app
    ports:
      - '8000:80'

  database:
    image: mariadb:10.6.5
    volumes:
      - ./database:/var/lib/mysql
#      - ./stage_dump_2023_02_01.sql:/dump/stage_dump_2023_02_01.sql
    ports:
      - '3306:3306'
#    command: --default-authentication-plugin=mysql_native_password
    #    command: --init-file /docker-entrypoint-initdb.d/stage_dump_2023_02_01.sql
    #    restart: always
    #      docker exec bubblebox-database-1 mysql -u root -psecret bubblebox < tests/_data/stage_dump_2023_02_01.sql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}